### ISSUE TITLE
Crash link to ROOT and Cling error when executing fecom program 

### ISSUE THREAD

**Issue by goliviero** [SuperNEMO-DBD/Falaise#36]
I'm working at cclyon with Yves's cadfael installation so I don't have any permission to update / upgrade and here is the path installation : `/sps/nemo/sw/simulation/install_brew/cadfaelbrew/`

My code located in trunk/companions/fecom/programs/hc_data_quality.cxx is not committed in this repository for the moment but here : https://github.com/SuperNEMO-DBD-France/Falaise/blob/fr-devel-fecom/companions/fecom/programs/hc_data_quality.cxx

When I try to execute my code on my local machine @ Caen with root 5, it works fine and the executable do the job.

However, when I try to execute the same code at CCLyon with root 6, here is the crash message I've got : 

```
[debug:void dpp::base_module::_common_initialize(const datatools::properties&):221] Exiting.
[warning:void dpp::io_common::initialize(const datatools::properties&, datatools::service_manager&):482] Module '' has no access to any 'context' service !

Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /scratch/nemoprod/_tmp/bayeux-20170607-145519-aj86un/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /scratch/nemoprod/_tmp/bayeux-20170607-145519-aj86un/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
Warning in <TStreamerInfo::BuildCheck>: 
   The StreamerInfo of class TArrayCMod read from file /sps/nemo/snemo/half_commissioning/serialized/Run_40/data/Run_40_0_events.brio
   has the same version (=1) as the active class but a different checksum.
   You should update the version to ClassDef(TArrayCMod,2).
   Do not try to write objects with the current class definition,
   the files will not be readable.

aborting
#0  0x0000003dabeac82e in waitpid () from /lib64/libc.so.6
#1  0x0000003dabe3e479 in do_system () from /lib64/libc.so.6
#2  0x00007feb2f1eee9a in TUnixSystem::StackTrace() () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libCore.so.6.08
#3  0x00007feb2f0fecaa in DefaultErrorHandler(int, bool, char const*, char const*) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libCore.so.6.08
#4  0x00007feb2f0fe773 in ErrorHandler () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libCore.so.6.08
#5  0x00007feb2f110354 in TObject::Warning(char const*, char const*, ...) const () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libCore.so.6.08
#6  0x00007feb2eb713e6 in TStreamerInfo::BuildCheck(TFile*) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libRIO.so.6.08
#7  0x00007feb2eb2de90 in TFile::ReadStreamerInfo() () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libRIO.so.6.08
#8  0x00007feb2eb3849f in TFile::Init(bool) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libRIO.so.6.08
#9  0x00007feb2eb39942 in TFile::TFile(char const*, char const*, char const*, int) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/root/libRIO.so.6.08
#10 0x00007feb30cb3c23 in brio::reader::_at_open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#11 0x00007feb30cb1d10 in brio::detail::base_io::open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#12 0x00007feb30cd304e in dpp::simple_brio_data_source::_open_file_source() () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#13 0x00007feb30cd3a8e in dpp::simple_brio_data_source::open() () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#14 0x00007feb30cd3c81 in dpp::simple_brio_data_source::simple_brio_data_source(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, datatools::logger::priority) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#15 0x00007feb30cc2cd4 in dpp::io_common::allocate_reader(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, datatools::logger::priority) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#16 0x00007feb30cc697b in dpp::input_module::_open_source() () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#17 0x00007feb30cc6fab in dpp::input_module::initialize(datatools::properties const&, datatools::service_manager&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, dpp::module_entry_type, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, dpp::module_entry_type> > >&) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#18 0x00007feb30cba7d5 in dpp::base_module::initialize_standalone(datatools::properties const&) () from /sps/nemo/sw/simulation/install_brew/cadfaelbrew/lib/libBayeux.so.3
#19 0x0000000000415484 in main ()
Aborted
```

I will try to install root6 on my local machine and see if the bug appears
I keep you in touch

**Comment by goliviero** [comment]
Ok, François give me a big clue on the error. The data I want to process were serialized with ROOT5 and I try to deserialize them with ROOT6 so it is not backward compatible because when I serialized the input data with ROOT6, the bug disapear

**Comment by drbenmorgan** [comment]
Right, this is related to #15 - it's not clear yet if this is brio bug or differences in the data/metadata layout (expected tree names). ROOT files created with v5 should be forward compatible, i.e. readable, with ROOT6.

**Comment by drbenmorgan** [comment]
Fecom is obsolete, so closing.
